// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHXTiKdj_2zQrcoU8PqPBubMdAAS0eZw0',
    appId: '1:110669120182:web:3ed85d86fb137935b09c17',
    messagingSenderId: '110669120182',
    projectId: 'arise-72bdd',
    authDomain: 'arise-72bdd.firebaseapp.com',
    storageBucket: 'arise-72bdd.firebasestorage.app',
    measurementId: 'G-D1KDHWY93X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfhPGI2cpw1QKA7tdk183hhBoHMSMVxI8',
    appId: '1:110669120182:android:07b7274facfae30bb09c17',
    messagingSenderId: '110669120182',
    projectId: 'arise-72bdd',
    storageBucket: 'arise-72bdd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1ZfGmDjmUGCMEjw-Kb9F5fwUC2-dO6rg',
    appId: '1:110669120182:ios:8b3858bc32833d58b09c17',
    messagingSenderId: '110669120182',
    projectId: 'arise-72bdd',
    storageBucket: 'arise-72bdd.firebasestorage.app',
    iosBundleId: 'com.example.arise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1ZfGmDjmUGCMEjw-Kb9F5fwUC2-dO6rg',
    appId: '1:110669120182:ios:8b3858bc32833d58b09c17',
    messagingSenderId: '110669120182',
    projectId: 'arise-72bdd',
    storageBucket: 'arise-72bdd.firebasestorage.app',
    iosBundleId: 'com.example.arise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHXTiKdj_2zQrcoU8PqPBubMdAAS0eZw0',
    appId: '1:110669120182:web:86bdef21cd56a46ab09c17',
    messagingSenderId: '110669120182',
    projectId: 'arise-72bdd',
    authDomain: 'arise-72bdd.firebaseapp.com',
    storageBucket: 'arise-72bdd.firebasestorage.app',
    measurementId: 'G-84YJ8RK5R0',
  );

}