// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx8u1L7azaBhe7XkYgDf0cigEdK_b2GyU',
    appId: '1:23344940897:web:a68fd6d6363e2d5a6ae720',
    messagingSenderId: '23344940897',
    projectId: 'arise-3d33b',
    authDomain: 'arise-3d33b.firebaseapp.com',
    storageBucket: 'arise-3d33b.firebasestorage.app',
    measurementId: 'G-G07660XD3X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpmVVQsLzmUIqu9H4EanSyGlAITUfxjPE',
    appId: '1:23344940897:android:575f05bf21d4a4a76ae720',
    messagingSenderId: '23344940897',
    projectId: 'arise-3d33b',
    storageBucket: 'arise-3d33b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPJCgWZA0aSvnXZUhJ66czP9dFC7aY4G4',
    appId: '1:23344940897:ios:251e360e05cdc3f86ae720',
    messagingSenderId: '23344940897',
    projectId: 'arise-3d33b',
    storageBucket: 'arise-3d33b.firebasestorage.app',
    iosBundleId: 'com.example.arise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPJCgWZA0aSvnXZUhJ66czP9dFC7aY4G4',
    appId: '1:23344940897:ios:251e360e05cdc3f86ae720',
    messagingSenderId: '23344940897',
    projectId: 'arise-3d33b',
    storageBucket: 'arise-3d33b.firebasestorage.app',
    iosBundleId: 'com.example.arise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDx8u1L7azaBhe7XkYgDf0cigEdK_b2GyU',
    appId: '1:23344940897:web:c15103d1280759a26ae720',
    messagingSenderId: '23344940897',
    projectId: 'arise-3d33b',
    authDomain: 'arise-3d33b.firebaseapp.com',
    storageBucket: 'arise-3d33b.firebasestorage.app',
    measurementId: 'G-NX53KDZMBN',
  );

}